tools: include hash and branch name in the changelog for tracing
canonical/core-base pull request #239
Opened 2024-08-27 07:39 UTC by Meulengracht

2024-08-27 12:30 UTC, Meulengracht commented on tools/generate-changelog.py
> +    changes = f"Built from commit: https://github.com/canonical/core-base/tree/{git_commit_hash()}\n\n"
Should we hardcode this URL or should we try to do some kind of magic with the ouput of `git remote get-url origin` to autogenerate it?

2024-08-29 21:00 UTC, alfonsosanchezbeato approved these changes
Thank you! I have some comments

2024-08-29 21:01 UTC, alfonsosanchezbeato requested changes
Sorry, I approved when I did not meant too

2024-09-04 10:12 UTC, Meulengracht commented on tools/generate-changelog.py
> +    changes += '[ Changes in primed packages ]\n\n'
https://paste.ubuntu.com/p/p94sfmZwDS/ this is how it looks now - I think the indentation is not needed tbh

2024-09-09 09:42 UTC, merged